server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: false
#          uri: https://github.com/SOA-labs/configs
          uri: file:///${user.home}/ITMO/soa/lab2/configs/
          search-paths: {application}
          default-label: changes-second-service-yml

#eureka:
#  client:
#    region: default
#    registry-fetch-interval-seconds: 15
#    serviceUrl:
#      defaultZone: http://localhost:9999/eureka/

